CRUD/Models/ErrorViewModel.cs
namespace CRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD/Controllers/EmployeeController.cs
using Crud.Core.Model;
using Crud.Entity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CRUD.Controllers
{
    public class EmployeeController : Controller
    {

        #region CREATE
        [HttpGet]
        public IActionResult Create()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7160/api/Emp/Create");
                var responseTask = client.GetAsync(client.BaseAddress);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    var readTask = result.Content.ReadFromJsonAsync<IList<LocDetails>>();
                    readTask.Wait();
                    ViewBag.Location = readTask.Result;

                }
            }
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmpDetails empdetails)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7160/api/Emp/Create");
                var Posttask = client.PostAsJsonAsync(client.BaseAddress, empdetails);
                Posttask.Wait();
                var result = Posttask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Read");
                }
            }
            return RedirectToAction("Read");
        }
        #endregion

        #region READ/LIST
        public IActionResult Read()
        {
            List<EmpDetails> studdetails = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7160/api/Emp/Read");
                var responseTask = client.GetAsync(client.BaseAddress);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadFromJsonAsync<IList<EmpDetails>>();
                    readTask.Wait();
                    studdetails = (List<EmpDetails>?)readTask.Result;
                }
                List<EmpDetails> sort = studdetails.OrderBy(a => a.FirstName).ToList();
                return View(sort);
            }
        }
        #endregion

        #region EDIT/UPDATE
        public IActionResult Edit(int id)
        {
            Create();
            EmpDetails student = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7160/api/Emp/Edit?id=");
                var responseTask = client.GetAsync(client.BaseAddress + id.ToString());
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadFromJsonAsync<EmpDetails>();
                    readTask.Wait();
                    student = readTask.Result;
                }
            }
            return View("Create", student);
        }
        #endregion

        #region DELETE
        public IActionResult Delete(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7160/api/Emp/Delete?id=");
                //HTTP DELETE
                var deleteTask = client.DeleteAsync(client.BaseAddress + id.ToString());
                deleteTask.Wait();
                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Read");
                }
            }
            return RedirectToAction("Read");
        }
        #endregion

        #region SEARCH
        public IActionResult Search(string search)
        {
            //if (!string.IsNullOrWhiteSpace(search))
            //{
            List<EmpDetails> studdetails = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7160/api/Emp/Search?search=");
                var responseTask = client.GetAsync(client.BaseAddress + search);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadFromJsonAsync<IList<EmpDetails>>();
                    readTask.Wait();
                    studdetails = (List<EmpDetails>?)readTask.Result;
                }
                //List<EmpDetails> sort = studdetails.OrderBy(a => a.FirstName).ToList();
                //return View("Read", sort);
                return View("Read",studdetails);
            }
            //}
            //else
            //{
            //    return RedirectToAction("Read");
            //}
        }
        #endregion

        #region DETAIL
        public IActionResult Detail(int id)
        {
            EmpDetails empdetails = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7160/api/Emp/Detail?id=");
                var responseTask = client.GetAsync(client.BaseAddress + id.ToString());
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadFromJsonAsync<EmpDetails>();
                    readTask.Wait();
                    empdetails = readTask.Result;
                }
            }
            return View(empdetails);
        }
        #endregion

    }
}

CRUD/Views/Employee/Create.cshtml
@model Crud.Core.Model.EmpDetails
@{
    Layout = null;
}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Form</title>
    <script src="./js/site.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="https://kit.fontawesome.com/a10c7f6efa.js" crossorigin="anonymous"></script>

    <style>
        .a {
            padding: 0px 0px 35px 0px;
        }
        .b{
           
            padding: 5px 10px 5px 10px;
        }
        
        body {
            margin: 0px 383px 10px 341px;
             /*margin: 0px 383px 10px 300px;*/
            background-color: lightgreen;
        }

        form {
            border: 1px solid black;
            border-radius: 25px;
            padding-left: 50px;
            padding-top: 10px;
            padding-bottom: 20px;
            background-color: skyblue;
        }
        .usericon{
            position:absolute;
            padding: 7px 0px 0px 9px;
        }
        input,textarea{
            padding:0px 0px 0px 35px;
        }
    </style>


</head>
@using (Html.BeginForm("Create", "Employee", FormMethod.Post, new { @id ="hemath" }))
{


    <body>
        <form>
            <center>
                <h2 class="a">EMPLOYEE DETAILS</h2>
            </center>
            @Html.HiddenFor(a=>a.EmployeeId, new{id="hiddenid"})

            <div class="a">
                FirstName<span style="color:red;">*</span>
                <i class="fa-solid fa-user usericon"></i>
                @Html.TextBoxFor(a=>a.FirstName,new{@placeholder="Enter your FirstName"})
            </div>
            <div class="a">
                LastName<span style="color:red;">*</span>
                <i class="fa-solid fa-user usericon"></i>
                @Html.TextBoxFor(a=>a.LastName,new{@placeholder="Enter your LastName"})
            </div>
            <div class="a">
                DateOfJoining<span style="color:red;">*</span>
                @Html.TextBoxFor(a=>a.Date,new { type="date" })
            </div>
            <div class="a">
                Age<span style="color:red;">*</span>
                <i class="fa-solid fa-cake-candles usericon"></i>
                @Html.TextBoxFor(a=>a.Age,new{@placeholder="Enter your Age"})
            </div>
            <div class="a">
                Experience<span style="color:red;">*</span>
                <i class="fa-solid fa-graduation-cap usericon"></i>
                @Html.TextBoxFor(a=>a.Experience,new{@placeholder="Enter your Experience"})
            </div>
            <div class="a">
                Contact Number<span style="color:red;">*</span>
                <i class="fa-solid fa-phone usericon "></i>
                @Html.TextBoxFor(a=>a.ContactNumber,new{@placeholder="Enter your ContactNumber"})
            </div>
            <div class="a">
                Address<span style="color:red;">*</span>
                <i class="fa-solid fa-location-dot usericon"></i>
                @Html.TextAreaFor(a=>a.Address,new{@placeholder="Enter Your Address"})
            </div>
            <div class="a">
                <label>Work Location</label>
                @Html.DropDownList("LocationId" , new SelectList(ViewBag.Location, "LocationId", "WorkLocation"), "Select Location")
            </div>
            <div class="a">
                Password<span style="color:red;">*</span>
                <i class="fa-solid fa-key usericon"></i>
                @Html.PasswordFor(a=>a.Password , new{id="password", @placeholder="Enter your Password"})
                <input type="checkbox" onclick="myFunction()">Show Password
            </div>
           
            <div class="a">
                Confirm Password<span style="color:red;">*</span>
                <i class="fa-solid fa-key usericon"></i>
                @Html.PasswordFor(a=>a.ConfirmPassword ,new{id="Confirm_Password",@placeholder="ReEnter Your Password"})
                <input type="checkbox" onclick="newFunction()">Show Password
            </div>
            <div class="a">
                <button type="submit" class="btn btn-success"  , onclick="Submit()", id="mybutton">Save</button>
                <input type="button" class="b" value="Go-To_Read" onclick="location.href='@Url.Action("Read", "Employee")'" />
             @*   <button class="btn btn-primary mb-3" type="reset">Reset</button>*@
            </div>


        </form>
    </body>
}
<script>
    $().ready(function () {

        $("#hemath").validate({
            // in 'rules' user have to specify all the constraints for respective fields
            rules:
            {

                FirstName:
                {
                    required: true,
                    lettersonly: true,
                },
                LastName:
                {
                    required: true,
                    lettersonly: true,
                },

               
                Date:
                {
                    required: true,
                },

                Age:
                {
                    required: true,
                },
                Experience:
                {
                    required: true,
                },
                ContactNumber:
                {

                    required: true,
                    number: true,
                    maxlength: 13,
                },
                Address:
                {
                    required: true,
                },
                Password:
                {
                    required: true,
                },
                ConfirmPassword:
                {
                    required: true,
                    equalTo: "#password"
                }

            },

            messages:
            {
                FirstName:
                {
                    required: " Please enter a FirstName",
                    lettersonly: "Only alphabets are valid"
                },
                LastName:
                {
                    required: " Please enter a FirstName",
                    lettersonly: "Only alphabets are valid"
                },

                
                Date:
                {
                    required: " Please enter a DateOFJoining"
                },


                Age:
                {
                    required: " Please enter a Age"
                },
                Experience:
                {
                    required: " Please enter a Experience"
                },
                ContactNumber:

                {
                    required: " Please enter a Phone Number",
                    maxlength: " Your number must not exceed 13 characters",
                },
                Address:
                {
                    required: " Please enter a Address",
                },


                Email:
                {
                    required: " Please enter a EmailId",
                },

                Password:
                {
                    required: " Please enter a password",
                },
                ConfirmPassword:
                {
                    required: " Please enter a password again",
                    equalTo: " Please enter the same password as entered above"
                }
            }

        });
        var eid = $("#hiddenid").val();
        if (eid != 0) {
            $("#mybutton").html("Update");
        }
    });


    function Submit() {
        if ($("#hemath").validate()) {
            $("#hemath").submit();
        }
    }


   
</script>

CRUD/Views/Employee/Detail.cshtml
@model Crud.Core.Model.EmpDetails

@{
    Layout = null;
}

<head>

</head>
<body>
    <div>
        <label>EmployeeId:</label>  
        @Html.DisplayFor(a=>a.EmployeeId)
    </div>
    <div>
        <label>FirstName: </label>      
        @Html.DisplayFor(a=>a.FirstName)
    </div>
    <div>
        <label>LastName: </label>
        @Html.DisplayFor(a=>a.LastName)
    </div>
    <div>
        <label>DateOfJoining: </label>
        @Html.DisplayFor(a=>a.Date)
    </div>
    <div>
        <label>Age:</label>
        @Html.DisplayFor(a=>a.Age)
    </div>
    <div>
        <label>Experience:</label>
        @Html.DisplayFor(a=>a.Experience)
    </div>
    <div>
        <label>ContactNumber:</label>
        @Html.DisplayFor(a=>a.ContactNumber)
    </div>
    <div>
        <label>Address:</label>
        @Html.DisplayFor(a=>a.Address)
    </div>
    <div>
        <label>WorkLocation:</label>
        @Html.DisplayFor(a=>a.WorkLocation)
    </div>
    <div>
        <label>Password:</label>
        @Html.DisplayFor(a=>a.Password)
    </div>
    <div>
        <label>ConfirmPassword:</label>
        @Html.DisplayFor(a=>a.ConfirmPassword)
    </div>

</body>

CRUD/Views/Employee/Read.cshtml
@model IEnumerable<Crud.Core.Model.EmpDetails>

@{
    Layout = null;
}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="https://kit.fontawesome.com/a10c7f6efa.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <style>
        .Table {
            border-collapse: collapse;
            /*  width: 100%;*/
            border: 1px solid #ddd;
            text-align: center;
        }

        th, td {
            padding: 15px;
            border: 1px solid #ddd;
            /*  width: 100%;*/
        }
    </style>
</head>
<h1>Read</h1>
<p>
    <input type="button" value="Create New Employee" onclick="location.href='@Url.Action("Create", "Employee")'" />
</p>
@using (Html.BeginForm("Search", "Employee", FormMethod.Get))
{
    <p>
        Find by  FirstName: @Html.TextBox("Search")
        <input type="submit" name="search" value="Search">
    </p>
}

<table class="Table">
    <tr>
        @*  <th> @Html.DisplayNameFor(a=>a.EmployeeId)</th>*@
        <th> @Html.DisplayNameFor(a=>a.FirstName)</th>
        <th> @Html.DisplayNameFor(a=>a.LastName)</th>
        <th> @Html.DisplayNameFor(a=>a.DateOfJoining)</th>
        <th> @Html.DisplayNameFor(a=>a.Age)</th>
        <th> @Html.DisplayNameFor(a=>a.Experience)</th>
        <th> @Html.DisplayNameFor(a=>a.ContactNumber)</th>
        <th> @Html.DisplayNameFor(a=>a.Address)</th>

        <th> @Html.DisplayNameFor(a=>a.WorkLocation)</th>

        <th> @Html.DisplayNameFor(a=>a.Password)</th>
        <th> @Html.DisplayNameFor(a=>a.ConfirmPassword)</th>
    </tr>

    @if(Model != null)
    {
    @foreach (var item in Model)
    {
        <tr>
            @*<td>@item.EmployeeId</td>*@
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.Date</td>
            <td>@item.Age</td>
            <td>@item.Experience</td>
            <td>@item.ContactNumber</td>
            <td>@item.Address</td>

            <td>@item.WorkLocation</td>

            <td>@item.Password</td>
            <td>@item.ConfirmPassword</td>
            <td>@Html.ActionLink("","Edit",new{id=item.EmployeeId},new{@class="fa-solid fa-pen-to-square",title="Edit"})</td>
            <td>
                <p type="submit" onclick="return confirm('Are you sure want to delete this record?')">
                    @Html.ActionLink("","Delete",new{id=item.EmployeeId},new{ @class="fa-solid fa-trash",title="Delete"})
                </p>
            </td>
            <td>
                <button style="background:white;border:none" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop" onclick="details('@item.EmployeeId')">
                    <i class="fa-solid fa-eye " ,title="Detail"></i>
                </button>
                <div class="modal fade" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Details</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body" id="mybody">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>

                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>

    }

    }
    else{
        <td> <p>no results founds</p> </td>
    }



</table>
<script>
    function details(id) {
        $("#myModal").css('display', 'block');
        $("#mybody").load("/Employee/Detail/" + id);
        $("#myModal").modal("show");
    }
</script>

CRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>